name: actions/docker-tag-exists
description: "Check if image tag exists and set env.docker_tag_exists accordingly"

inputs:
  tag:
    description: "The image Tag address e.g. ghcr.io/owner/repo:tag"
    required: true

runs:
  using: composite
  steps:
    - name: Inspect docker manifest for specified tag
      shell: sh
      run: |
        set -euo
        if docker manifest inspect ${{ inputs.tag }} > /dev/null 2>&1; then
          echo "Tag ${{ inputs.tag }} already exists. docker_tag_exists=true"
          echo "docker_tag_exists=true" >> $GITHUB_ENV
        else
          echo "Tag ${{ inputs.tag }} does not exist. docker_tag_exists=false"
          echo "docker_tag_exists=false" >> $GITHUB_ENV
        fi
